name: Delete Older Releases of Repos
description: Automatic delete older releases action of any repo
author: Vucko130

branding:
  color: red
  icon: trash-2

inputs:
  keep_latest:
    description: how many latest releases to keep
    required: true
  repo:
    description: repo name in the form of <owner>/<repoName>
    required: false
  delete_tags:
    description: whether to delete tags associated to older releases or not
    required: false
  delete_tag_pattern:
    description: part of the tag name. Example, if you want to delete 0.0.1-beta and 0.0.2-beta but not 0.0.1 then set this to just "beta". If not set then it will target all releases.
    required: false
  regex:
    description: whether to use regex matching for the given pattern against the tag name
    required: false
    default: false

runs:
  using: "node16"
  main: "index.js"
